const schedule=[{start:'09:00',end:'12:00',title:'上午复习',sub:'建立今天的节奏',minutes:180},{start:'13:30',end:'18:00',title:'下午复习',sub:'完成当天的主要任务',minutes:270},{start:'20:30',end:'23:00',title:'晚间复习',sub:'收束、巩固与整理',minutes:150}];
const rest=[{start:'12:00',end:'13:30',title:'午饭与休息',sub:'离开书桌，真正休息'},{start:'18:00',end:'20:30',title:'晚饭与休息',sub:'给大脑换个频道'},{start:'23:00',end:'次日 09:00',title:'陪伴与睡眠',sub:'今天到这里'}];
const key='focus-guardian-v1', syncEndpoint=window.FOCUS_SYNC_ENDPOINT||'api/sync.php', syncToken=window.FOCUS_SYNC_TOKEN||''; let data=JSON.parse(localStorage.getItem(key)||'null')||{tasks:[],ideas:[],focused:0,interruptions:0,streak:0,review:'',checkins:{},settings:{backgroundMode:false}}; data.checkins=data.checkins||{}; data.settings=data.settings||{}; data.settings.backgroundMode=!!data.settings.backgroundMode; data.updatedAt=data.updatedAt||0; let active=null, elapsed=0, timerId=null, timerSource='local', syncBusy=false, syncPending=false; let calendarDate=new Date();
const $=id=>document.getElementById(id); const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()}; const mins=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};
function syncHeaders(){return {'Content-Type':'application/json',...(syncToken?{'X-Sync-Token':syncToken}:{})}}
function setSyncStatus(text,good=false){const el=$('syncStatus');if(el){el.textContent=text;el.classList.toggle('online',good)}}
async function syncToServer(){if(syncBusy){syncPending=true;return}syncBusy=true;try{const r=await fetch(syncEndpoint,{method:'PUT',headers:syncHeaders(),cache:'no-store',body:JSON.stringify(data)});if(!r.ok)throw new Error('sync failed');const payload=await r.json();if(payload.data&&payload.data.updatedAt>data.updatedAt){data=normalizeRemote(payload.data);localStorage.setItem(key,JSON.stringify(data));render()}localStorage.setItem('focus-sync-initialized','1');setSyncStatus('已同步',true)}catch(e){setSyncStatus('离线')}finally{syncBusy=false;if(syncPending){syncPending=false;syncToServer()}}}
function normalizeRemote(value){value=value||{};value.tasks=value.tasks||[];value.ideas=value.ideas||[];value.checkins=value.checkins||{};value.settings=value.settings||{};value.settings.backgroundMode=!!value.settings.backgroundMode;return value}
async function syncFromServer(){if(syncBusy){syncPending=true;return}syncBusy=true;let uploadAfter=false;try{const r=await fetch(syncEndpoint,{headers:syncHeaders(),cache:'no-store'});if(!r.ok)throw new Error('sync failed');const payload=await r.json();if(payload.data){data=normalizeRemote(payload.data);localStorage.setItem(key,JSON.stringify(data));localStorage.setItem('focus-sync-initialized','1');render()}else if(!localStorage.getItem('focus-sync-initialized')&&(data.tasks.length||data.ideas.length||data.focused||Object.keys(data.checkins).length||data.timer?.running)){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));uploadAfter=true}else{localStorage.setItem('focus-sync-initialized','1')}setSyncStatus('已同步',true)}catch(e){setSyncStatus('本地')}finally{syncBusy=false;if(uploadAfter||syncPending){syncPending=false;syncToServer()}}}
function save(){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));syncToServer()} function currentSession(){const n=nowMinutes();return schedule.find(s=>n>=mins(s.start)&&n<mins(s.end))||schedule[0]}
function renderTimeline(){const n=nowMinutes();$('timeline').innerHTML=[...schedule,...rest].sort((a,b)=>mins(a.start)-mins(b.start)).map(s=>{const is=s.start!=='次日 09:00'&&n>=mins(s.start)&&n<mins(s.end);return `<div class="timeline-row ${is?'active':''}"><span class="time">${s.start}<br>${s.end}</span><div><div class="timeline-title">${s.title}</div><div class="timeline-sub">${s.sub}</div></div><span class="timeline-badge">${is?'进行中':s.start==='次日 09:00'?'休息':'计划'}</span></div>`}).join('')}
function renderTasks(){ $('taskList').innerHTML=data.tasks.map((t,i)=>`<div class="task-item ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-i="${i}"><label>${escapeHtml(t.text)}</label><button class="delete-task" data-del="${i}" aria-label="删除">×</button></div>`).join('')||'<div class="empty">还没有任务，先写下这一段要完成的事。</div>'; $('taskCount').textContent=`${data.tasks.filter(t=>t.done).length}/${data.tasks.length||3}`}
function renderIdeas(){$('ideaList').innerHTML=data.ideas.map(i=>`<li>${escapeHtml(i.text)}<small>${i.time}</small></li>`).join('')||'<li class="empty">收集箱是空的，保持这份清爽。</li>';$('inboxCount').textContent=`${data.ideas.length} 条`}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=`${y} 年 ${m+1} 月`;const first=new Date(y,m,1);const offset=(first.getDay()+6)%7;const total=new Date(y,m+1,0).getDate();const today=dateKey(new Date());let html='';for(let i=0;i<offset;i++)html+='<span class="calendar-day empty-day"></span>';for(let d=1;d<=total;d++){const date=new Date(y,m,d),keyDate=dateKey(date),checked=!!data.checkins[keyDate];html+=`<button class="calendar-day ${keyDate===today?'today ':''}${checked?'checked':''}" data-date="${keyDate}" aria-label="${keyDate}${checked?' 已签到':''}"><span>${d}</span>${checked?'<i>✓</i>':''}</button>`}$('calendar').innerHTML=html;const todayChecked=!!data.checkins[today];$('checkinBtn').textContent=todayChecked?'今日已签到':'签到打卡';$('checkinBtn').disabled=todayChecked;$('checkinMessage').textContent=todayChecked?'今天的努力已经留下记录。':'觉得今天学得不错，就给自己留一个标记。'}
function updateStats(){const target=schedule.reduce((a,s)=>a+s.minutes,0);const p=Math.min(100,Math.round(data.focused/target*100));$('progressPercent').textContent=`${p}%`;$('progressBar').style.width=p+'%';$('focusedMinutes').textContent=`${data.focused} 分钟`;$('interruptions').textContent=`${data.interruptions} 次`;$('streak').textContent=`${data.streak} 天`}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){const sunday=new Date().getDay()===0;const s=currentSession();$('sessionName').textContent=sunday?'休息日':s.title;$('todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});$('dayStatus').textContent=sunday?'今天休息':'准备开始';$('backgroundMode').checked=data.settings.backgroundMode;renderTimeline();renderTasks();renderIdeas();updateStats();renderCalendar();$('reviewInput').value=data.review||'';if(data.timer?.running)applyRemoteTimer()}
function tick(){if(data.timer?.running)elapsed=Math.max(0,Math.floor((Date.now()-data.timer.startedAt)/1000)); const h=String(Math.floor(elapsed/3600)).padStart(2,'0'),m=String(Math.floor(elapsed%3600/60)).padStart(2,'0'),s=String(elapsed%60).padStart(2,'0');$('timer').textContent=`${h}:${m}:${s}`}
function start(){if(timerId)return;active=true;timerSource='local';data.timer={running:true,startedAt:Date.now()-elapsed*1000,elapsed};save();tick();timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('finishBtn').disabled=false;$('timerHint').textContent='保持这一件事，其他念头放进收集箱';$('dayStatus').textContent='专注中'} function pause(){if(data.timer?.running){tick();data.timer={running:false,startedAt:0,elapsed};save()}clearInterval(timerId);timerId=null;$('startBtn').disabled=false;$('pauseBtn').disabled=true;$('dayStatus').textContent='已暂停'} function finish(){if(!active)return;tick();pause();data.focused+=Math.max(1,Math.round(elapsed/60));data.streak=Math.max(data.streak,1);data.timer={running:false,startedAt:0,elapsed:0};save();elapsed=0;active=false;$('timer').textContent='00:00:00';$('finishBtn').disabled=true;$('timerHint').textContent='这一段完成了，休息一下再继续';render();}
function applyRemoteTimer(){const t=data.timer;if(!t?.running){if(active&&timerSource==='remote'){clearInterval(timerId);timerId=null;active=false;elapsed=0;$('timer').textContent='00:00:00';$('startBtn').disabled=false;$('pauseBtn').disabled=true;$('finishBtn').disabled=true;$('dayStatus').textContent='已暂停'}return}if(!active){active=true;timerSource='remote';elapsed=Math.max(0,Math.floor((Date.now()-t.startedAt)/1000));clearInterval(timerId);timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('finishBtn').disabled=false;$('dayStatus').textContent='专注中（其他设备）';tick()}}
function openIdea(prefill=''){ $('modalInput').value=prefill;$('ideaModal').classList.remove('hidden');$('modalInput').focus() } function addIdea(text){text=text.trim();if(!text)return;data.ideas.unshift({text,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});save();renderIdeas();$('ideaModal').classList.add('hidden')}
$('startBtn').onclick=start;$('pauseBtn').onclick=pause;$('finishBtn').onclick=finish;$('taskForm').onsubmit=e=>{e.preventDefault();const t=$('taskInput').value.trim();if(t){data.tasks.push({text:t,done:false});$('taskInput').value='';save();renderTasks()}};$('taskList').onclick=e=>{const i=e.target.dataset.i;if(i!==undefined){data.tasks[i].done=e.target.checked;save();renderTasks()}const d=e.target.dataset.del;if(d!==undefined){data.tasks.splice(d,1);save();renderTasks()}};$('ideaForm').onsubmit=e=>{e.preventDefault();addIdea($('ideaInput').value);$('ideaInput').value=''};$('modalSave').onclick=()=>addIdea($('modalInput').value);$('modalClose').onclick=()=>$('ideaModal').classList.add('hidden');$('overlayClose').onclick=()=>$('focusOverlay').classList.add('hidden');$('overlayCollect').onclick=()=>{ $('focusOverlay').classList.add('hidden');openIdea()};$('saveReview').onclick=()=>{data.review=$('reviewInput').value.trim();save();$('reviewSaved').textContent='已保存';setTimeout(()=>$('reviewSaved').textContent='',1800)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!data.settings.backgroundMode){data.interruptions++;save();$('overlayTitle').textContent='刚才离开了一下';$('overlayMessage').textContent='把注意力带回当前任务。想做的事可以先记下，今晚再处理。';$('focusOverlay').classList.remove('hidden');updateStats()}});
document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA'].includes(tag))openIdea();});
const savedTheme=localStorage.getItem('focus-theme');if(savedTheme==='dark')document.body.classList.add('dark');$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('focus-theme',document.body.classList.contains('dark')?'dark':'light')};$('backgroundMode').onchange=e=>{data.settings.backgroundMode=e.target.checked;save()};if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});setInterval(renderTimeline,60000);setInterval(()=>{if(active){data.timer={running:true,startedAt:data.timer?.startedAt||Date.now()-elapsed*1000,elapsed};data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));syncToServer()}else syncFromServer()},10000);syncFromServer();render();
$('checkinBtn').onclick=()=>{const today=dateKey(new Date());if(!data.checkins[today]){data.checkins[today]={at:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})};save();renderCalendar()}};$('prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('calendar').onclick=e=>{const day=e.target.closest('[data-date]');if(!day)return;const k=day.dataset.date;if(data.checkins[k]){delete data.checkins[k];save();renderCalendar()}};
