const defaultTimeline=['09:00','12:00','13:30','18:00','20:30','23:00'];
const schedule=[{start:'09:00',end:'12:00',title:'上午复习',sub:'建立今天的节奏'},{start:'13:30',end:'18:00',title:'下午复习',sub:'完成当天的主要任务'},{start:'20:30',end:'23:00',title:'晚间复习',sub:'收束、巩固与整理'}];
const rest=[{start:'12:00',end:'13:30',title:'午饭与休息',sub:'离开书桌，真正休息'},{start:'18:00',end:'20:30',title:'晚饭与休息',sub:'给大脑换个频道'},{start:'23:00',end:'09:00',title:'陪伴与睡眠',sub:'今天到这里',overnight:true}];
const planStart='2026-09-01',planEnd='2026-10-15',planCache={};
const planCatalog={
  high:Array.from({length:20},(_,i)=>`武忠祥高数强化 第${i+5}节`),
  probabilityFoundation:[
    '01 知识切片1 排列与组合','02 知识切片2 事件的关系与运算','03 知识切片3 古典概率与几何模型','04 知识切片4 概率的定义及性质','05 知识切片5 条件概率及其性质','06 知识切片6 全概率公式和贝叶斯公式','07 知识切片7 事件的独立性','08 知识切片8 n重伯努利模型与概率计算',
    '切片1 随机变量的概念及分布','切片2 一维离散型随机变量及其分布（1）','切片3 常见的离散型分布（1）','切片4 一维连续型随机变量及其分布（1）','切片5 常见的一维连续型分布','切片6 一维随机变量函数的分布',
    '切片1 二维随机变量的概念及其分布','切片2 二维离散型随机变量及其分布','切片3 二维连续型随机变量及其分布','切片4 两个常见的二维连续型分布','切片5 两个连续型随机变量函数的分布（1）','切片6 两个连续型随机变量函数的分布（2）','切片7 离散型与连续型随机变量函数的分布',
    '切片1 随机变量的期望','切片2 随机变量的方差','切片3 随机变量的矩与协方差','切片4 随机变量的相关系数','切片1 切比雪夫不等式','切片2 大数定律','切片3 中心极限定理','切片1 总体与样本','切片2 统计量','切片3 三大分布','切片4 正态总体的抽样分布','切片1 矩估计','切片2 最大似然估计','切片3 估计量的评选标准（数学一）','切片4 区间估计（置信区间）（数学一）','切片5 假设检验（数学一）'
  ],
  linear:[
    '第1章-基本内容和重要结论','第1章-例题讲解','第1章-习题讲解','第2章-基本概念和重要结论','第2章-例题讲解','第2章-习题讲解','第3章-基本内容和重要结论','第3章-例题讲解','第3章-习题讲解','第4章-基本内容和重要结论','第4章-例题讲解','第4章-习题讲解','第5章-基本内容和重要结论','第5章-例题讲解','第5章-习题讲解','第6章-基本内容和重要结论','第6章-例题讲解','第6章-习题讲解','第7章-基本内容和重要结论','第7章-例题讲解','第7章-习题讲解'
  ],
  probabilityReinforce:[
    '01 gq-01','01 gq1-01 随机事件的概念、关系与运算','02 gq-02','02 gq1-02 随机事件的概率','03 gq1-03 事件的独立性','04 gq1-04（题型一）事件的关系与运算','05 gq1-05（题型二）概率的性质与应用','06 gq1-06（题型三）条件概率的运算','07 gq1-07（题型四）二大模型','08 gq1-08（题型五）随机事件的独立性1','09 gq1-09（题型五）随机事件的独立性2','10 gq2-01 随机变量及其分布函数','11 gq2-02 离散型随机变量','12 gq2-03 连续性随机变量','13 gq2-04 随机变量函数的分布','14 gq2-05（题型一）分布函数的概念与性质1','15 gq2-06（题型一）分布函数的概念与性质2','16 gq2-07（题型二）一维离散型随机变量及其分布1','17 gq2-08（题型二）一维离散型随机变量及其分布2','18 gq2-09（题型三）一维连续型随机变量及其分布1','19 gq2-10（题型三）一维连续型随机变量及其分布2','19 gq2-11（题型四）一维随机变量函数的分布1','21 gq2-12（题型四）一维随机变量函数的分布2','22 gq3-01多维随机变量及其分布（概念）1','23 gq3-02多维随机变量及其分布（概念）2','24 gq3-03多维随机变量及其分布（概念）3','25 gq3-04（题型一）二维随机变量的分布函数','26 gq3-05（题型二）二维离散型随机变量','27 gq3-06（题型二）二维连续型随机变量','28 gq3-07（题型四）二维均匀分布、二维正态分布1','29 gq3-08（题型四）二维均匀分布、二维正态分布2','30 gq3-09（题型五）二维离散型随机变量函数的分布','31 gq3-10（题型六）二维连续型随机变量函数的分布1','32 gq3-11（题型六）二维连续型随机变量函数的分布2','33 gq3-12（题型七）二维混合型随机变量','34 gq3-13（题型八）max型和min型随机变量的分布函数','35 gq4-01随机变量的数学期望','36 gq4-02随机变量的方差（1）','37 gq4-03协方差与相关系数','38 gq4-04随机变量的矩','39 gq4-05（题型一）期望与方差的一般计算1','40 gq4-06（题型一）期望与方差的一般计算2','41 gq4-07（题型一）期望与方差的一般计算3','42 gq4-08（题型一）期望与方差的一般计算4','43 gq4-09（题型二）绝对值型期望与方差的计算','44 gq4-10（题型三）运用降维法计算期望与方差','45 gq4-11（题型四）协方差与相关系数的计算1','46 gq4-12（题型四）协方差与相关系数的计算2','47 gq4-13（题型四）协方差与相关系数的计算3','48 gq4-14（题型五）随机变量的不相关性','49 gq4-15（题型六）随机变量的不相关性与独立性的关系1','50 gq4-16（题型六）随机变量的不相关性与独立性的关系2','51 gq5-01切比雪夫不等式','52 gq5-02大数定律','53 gq5-03中心极限定理','54 gq5-04（题型一）切比雪夫不等式','55 gq5-05（题型二）大数定律','56 gq5-06（题型三）中心极限定理','57 gq6-01随机样本','58 gq6-02统计量及其分布','59 gq6-03正态总体的常用统计分布','60 gq6-04（题型一）常用统计量及数字特征','61 gq6-05（题型二）三大分布1','62 gq6-06（题型二）三大分布2','63 gq6-07（题型三）单正态总体的抽样分布','64 gq6-08（题型四）双正态总体的抽样分布','65 gq7-01点估计','66 gq7-02估计量的评选标准（数学一）','67 gq7-03区间估计（数学一）','68 gq7-04（题型一）点估计及点估计的数字特征','69 gq7-05（题型二）估计量评选标准（数学一）','70 gq7-06（题型三）置信区间（数学一）','71 gq8-01假设检验的概念','72 gq8-02显著性检验','73 gq8-03（题型一、二、三）'
  ]
};
const planCourseNames={high:'高数强化',linear:'线性代数强化',probabilityFoundation:'概率论基础',probabilityReinforce:'概率论强化',professional:'专业课'};
const key='focus-guardian-v1', syncEndpoint=window.FOCUS_SYNC_ENDPOINT||'api/sync.php', syncToken=window.FOCUS_SYNC_TOKEN||''; let storedData=null;try{storedData=JSON.parse(localStorage.getItem(key)||'null')}catch(e){localStorage.removeItem(key)}let data=normalizeRemote(storedData);let active=null,elapsed=0,timerId=null,timerSource='local',writeBusy=false,writePending=false,readBusy=false,resumeAfterLeave=false;let calendarDate=new Date();
const $=id=>document.getElementById(id); const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()}; const mins=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};
function syncHeaders(){return {'Content-Type':'application/json',...(syncToken?{'X-Sync-Token':syncToken}:{})}}
function setSyncStatus(text,good=false){const el=$('syncStatus');if(el){el.textContent=text;el.classList.toggle('online',good)}}
async function syncToServer(){if(writeBusy){writePending=true;return}writeBusy=true;const snapshot=JSON.stringify(data);try{const r=await fetch(syncEndpoint,{method:'PUT',headers:syncHeaders(),cache:'no-store',body:snapshot});if(!r.ok)throw new Error('sync failed');await r.json();localStorage.setItem('focus-sync-initialized','1');setSyncStatus('已同步',true)}catch(e){setSyncStatus('离线')}finally{writeBusy=false;if(writePending||JSON.stringify(data)!==snapshot){writePending=false;syncToServer()}}}
function timelineIsValid(values){return Array.isArray(values)&&values.length===6&&values.every(v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v))&&values.every((v,i)=>i===0||timeToMinutes(values[i-1])<timeToMinutes(v))}
function timeToMinutes(value){const [h,m]=value.split(':').map(Number);return h*60+m}
function applyTimelineConfig(values){const b=timelineIsValid(values)?values.slice():defaultTimeline.slice();schedule[0].start=b[0];schedule[0].end=b[1];rest[0].start=b[1];rest[0].end=b[2];schedule[1].start=b[2];schedule[1].end=b[3];rest[1].start=b[3];rest[1].end=b[4];schedule[2].start=b[4];schedule[2].end=b[5];rest[2].start=b[5];rest[2].end=b[0];return b}
function normalizeTask(task,index){if(typeof task==='string')task={text:task};task=task&&typeof task==='object'?task:{};const text=String(task.text||'').trim();return {id:String(task.id||`legacy-${index}`),text,done:!!task.done,createdAt:Number(task.createdAt)||0,dayKey:/^\d{4}-\d{2}-\d{2}$/.test(task.dayKey||'')?task.dayKey:studyDayKey(),sessionKey:String(task.sessionKey||'legacy'),sessionTitle:String(task.sessionTitle||'历史任务')}}
function normalizeRemote(value){value=value||{};value.tasks=(Array.isArray(value.tasks)?value.tasks:[]).map(normalizeTask).filter(task=>task.text);value.ideas=Array.isArray(value.ideas)?value.ideas:[];value.checkins=value.checkins&&typeof value.checkins==='object'&&!Array.isArray(value.checkins)?value.checkins:{};value.planChecks=value.planChecks&&typeof value.planChecks==='object'&&!Array.isArray(value.planChecks)?value.planChecks:{};value.planEdits=value.planEdits&&typeof value.planEdits==='object'&&!Array.isArray(value.planEdits)?value.planEdits:{};value.planDeletes=value.planDeletes&&typeof value.planDeletes==='object'&&!Array.isArray(value.planDeletes)?value.planDeletes:{};value.dailyFocus=value.dailyFocus&&typeof value.dailyFocus==='object'&&!Array.isArray(value.dailyFocus)?value.dailyFocus:{};value.timeline=applyTimelineConfig(value.timeline);value.settings=value.settings||{};if(localStorage.getItem('focus-background-mode')===null&&typeof value.settings.backgroundMode==='boolean')localStorage.setItem('focus-background-mode',value.settings.backgroundMode?'1':'0');delete value.settings.backgroundMode;value.focused=Number(value.focused)||0;value.interruptions=Number(value.interruptions)||0;value.streak=Number(value.streak)||0;value.review=value.review||'';value.updatedAt=Number(value.updatedAt)||0;return value}
async function syncFromServer(){if(readBusy||writeBusy)return;readBusy=true;let uploadAfter=false;const localVersion=data.updatedAt;try{const r=await fetch(syncEndpoint,{headers:syncHeaders(),cache:'no-store'});if(!r.ok)throw new Error('sync failed');const payload=await r.json();if(payload.data&&Number(payload.data.updatedAt||0)>Number(localVersion||0)){data=normalizeRemote(payload.data);localStorage.setItem(key,JSON.stringify(data));localStorage.setItem('focus-sync-initialized','1');render()}else if(payload.data&&Number(localVersion||0)>Number(payload.data.updatedAt||0)){uploadAfter=true}else if(payload.data===null&&!localStorage.getItem('focus-sync-initialized')&&(data.tasks.length||data.ideas.length||data.focused||Object.keys(data.checkins).length||data.timer?.running)){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));uploadAfter=true}else if(payload.data===null){localStorage.setItem('focus-sync-initialized','1')}setSyncStatus('已同步',true)}catch(e){setSyncStatus('本地')}finally{readBusy=false;if(uploadAfter)syncToServer()}}
function save(){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));syncToServer()} function recordDailyFocus(day,minutes){if(!day)return 0;const next=Math.max(0,Math.floor(Number(minutes)||0)),previous=Math.max(0,Math.floor(Number(data.dailyFocus[day])||0));if(next>previous)data.dailyFocus[day]=next;return Math.max(previous,next)} function isInWindow(s,n){const start=mins(s.start),end=mins(s.end);return s.overnight?n>=start||n<end:n>=start&&n<end} function currentSession(){const n=nowMinutes();return [...schedule,...rest].find(s=>isInWindow(s,n))||rest[2]}
function displayEnd(period){return period.overnight?`次日 ${period.end}`:period.end}
function periodKey(s){return `${s.start}-${s.end}`}
function showPeriodReminder(previous,current){const title=`${current.title}开始`,$modal=$('reminderModal');$('reminderTitle').textContent=title;$('reminderMessage').textContent=previous?`${previous.title}已结束。现在进入 ${current.start}–${displayEnd(current)} 的${current.title}。`:`现在进入 ${current.start}–${displayEnd(current)} 的${current.title}。`;if(document.visibilityState==='visible')$modal.classList.remove('hidden');else if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body:$('reminderMessage').textContent,icon:'assets/zinhologo.jpg'})}
function checkPeriodTransition(){const current=currentSession(),currentKey=periodKey(current),previousKey=localStorage.getItem('focus-last-period');if(previousKey&&previousKey!==currentKey&&localStorage.getItem('focus-schedule-reminders')==='1'&&new Date().getDay()!==0){const previous=[...schedule,...rest].find(s=>periodKey(s)===previousKey);showPeriodReminder(previous,current)}localStorage.setItem('focus-last-period',currentKey)}
function fillScheduleForm(values){values.forEach((value,index)=>$('scheduleTime'+index).value=value)}
function openScheduleEditor(){$('scheduleError').textContent='';fillScheduleForm(data.timeline);$('scheduleModal').classList.remove('hidden')}
function saveScheduleEditor(event){event.preventDefault();const values=defaultTimeline.map((_,index)=>$('scheduleTime'+index).value);if(!timelineIsValid(values)){$('scheduleError').textContent='六个时间必须按当天先后顺序排列，且不能相同。';return}data.timeline=applyTimelineConfig(values);localStorage.setItem('focus-last-period',periodKey(currentSession()));save();render();$('scheduleModal').classList.add('hidden')}
function renderTimeline(){const n=nowMinutes(),today=dateKey(new Date());$('timeline').innerHTML=[...schedule,...rest].sort((a,b)=>mins(a.start)-mins(b.start)).map(s=>{const is=isInWindow(s,n),period=planForSession(today,s),periodId=planIdForSession(s),custom=periodId?customTasksForPeriod(today,periodId):[],hasTasks=!!period?.tasks?.length||custom.length>0,planHtml=hasTasks?`<div class="timeline-plan">${period?.tasks.map(task=>planTaskMarkup(task,true)).join('')||''}${custom.map(task=>customTaskMarkup(task,true)).join('')}</div>`:'';return `<div class="timeline-row ${is?'active':''}"><span class="time">${s.start}<br>${displayEnd(s)}</span><div><div class="timeline-title">${s.title}</div>${hasTasks?'':`<div class="timeline-sub">${escapeHtml(s.sub)}</div>`}${planHtml}</div><span class="timeline-badge">${is?'进行中':hasTasks?'今日任务':'计划'}</span></div>`}).join('')}
function taskBelongsToCurrent(task){const today=studyDayKey(),period=periodKey(currentSession());return task.dayKey===today&&(task.sessionKey==='legacy'||task.sessionKey===period)}
function renderTasks(){const visible=data.tasks.map((task,index)=>({task,index})).filter(item=>taskBelongsToCurrent(item.task)),period=planForSession(dateKey(new Date()),currentSession()),planned=period?.tasks||[],plannedDone=planned.filter(task=>data.planChecks?.[task.id]).length,customDone=visible.filter(({task})=>task.done).length;const plannedHtml=planned.length?`<div class="planned-task-group"><div class="planned-task-label">本段计划目标</div>${planned.map(task=>planTaskMarkup(task)).join('')}</div>`:'';const customHtml=visible.map(({task})=>`<div class="task-item ${task.done?'done':''}"><input type="checkbox" ${task.done?'checked':''} data-task-id="${escapeHtml(task.id)}"><label>${escapeHtml(task.text)}</label><button class="delete-task" data-task-del="${escapeHtml(task.id)}" aria-label="删除">×</button></div>`).join('');$('taskList').innerHTML=plannedHtml+(customHtml||(!planned.length?'<div class="empty">还没有任务，先写下这一段要完成的事。</div>':''));$('taskCount').textContent=`${plannedDone+customDone}/${planned.length+visible.length||3}`}
function formatTaskDate(day){if(!/^\d{4}-\d{2}-\d{2}$/.test(day||''))return'未记录日期';const [y,m,d]=day.split('-');return`${y}年${Number(m)}月${Number(d)}日`}
function renderTaskHistory(){const groups={};data.tasks.forEach(task=>{const day=task.dayKey||'未记录日期';(groups[day]??=[]).push(task)});const days=Object.keys(groups).sort((a,b)=>b.localeCompare(a));$('taskHistoryList').innerHTML=days.map(day=>{const tasks=groups[day].slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));return`<section class="task-history-group"><h3>${formatTaskDate(day)}</h3>${tasks.map(task=>`<div class="history-task ${task.done?'done':''}"><span>${task.done?'✓':'○'}</span><div><strong>${escapeHtml(task.text)}</strong><small>${escapeHtml(task.sessionTitle||'历史任务')}</small></div></div>`).join('')}</section>`}).join('')||'<div class="empty">还没有历史任务记录。</div>'}
function renderIdeas(){$('ideaList').innerHTML=data.ideas.map(i=>`<li>${escapeHtml(i.text)}<small>${i.time}</small></li>`).join('')||'<li class="empty">收集箱是空的，保持这份清爽。</li>';$('inboxCount').textContent=`${data.ideas.length} 条`}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
// The study day runs from 03:00 to 02:59 the next calendar day. This keeps late-night study attached to the previous day.
function studyDayKey(d=new Date()){const value=new Date(d);if(value.getHours()<3)value.setDate(value.getDate()-1);return dateKey(value)}
function dateFromKey(key){const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d,12,0,0)}
function rangeKeys(start,end){const keys=[],date=dateFromKey(start),last=dateFromKey(end);while(date<=last){keys.push(dateKey(date));date.setDate(date.getDate()+1)}return keys}
function isSundayKey(key){return dateFromKey(key).getDay()===0}
function allocatePlanVideos(course,days){const groups={};days.forEach(day=>{groups[day]=[]});const catalog=planCatalog[course]||[];catalog.forEach((video,index)=>{if(!days.length)return;const slot=Math.min(days.length-1,Math.floor(index*days.length/catalog.length));groups[days[slot]].push(video)});return groups}
function planCourseCode(day,kind){if(kind!=='probability')return kind;return day<='2026-09-21'?'probabilityFoundation':'probabilityReinforce'}
function planCourseLabel(code){return planCourseNames[code]||code}
function planTask(day,period,code,kind,videos){const name=planCourseLabel(code),hasVideo=videos&&videos.length;const text=kind==='video'?(hasVideo?`${name}：\n${videos.join('\n')}`:`${name}：回顾已学内容与错题`):`${name}：例题、课后题与错题订正`;return{id:`plan-${day}-${period}-${code}-${kind}`,course:code,text}}
function professionalPlanTask(day){return{id:`plan-${day}-evening-professional`,course:'professional',text:'专业课：学习 2 小时（课程待定）'}}
function buildStudyPlan(){if(planCache.value)return planCache.value;const allDays=rangeKeys(planStart,planEnd),studyDays=allDays.filter(day=>!isSundayKey(day)),pairs=['high-probability','high-linear','probability-linear'],pairByDay={};studyDays.forEach((day,index)=>{pairByDay[day]=pairs[Math.floor(index/3)%pairs.length]});const activeDays={high:studyDays.filter(day=>day<='2026-10-11'&&pairByDay[day].includes('high')),linear:studyDays.filter(day=>day<='2026-09-27'&&pairByDay[day].includes('linear')),probabilityFoundation:studyDays.filter(day=>day<='2026-09-21'&&pairByDay[day].includes('probability')),probabilityReinforce:studyDays.filter(day=>day>='2026-09-22'&&pairByDay[day].includes('probability'))};const allocations={};Object.keys(activeDays).forEach(code=>{allocations[code]=allocatePlanVideos(code,activeDays[code])});const plan={};allDays.forEach(day=>{if(isSundayKey(day)){plan[day]={day,rest:true,title:'休息日',periods:{}};return}const pair=pairByDay[day].split('-').map(code=>code==='probability'?planCourseCode(day,'probability'):code),morning=pair.includes('high')?'high':pair[0],afternoon=pair.find(code=>code!==morning)||morning,periods={};const addPeriod=(id,course,goal)=>{const videos=allocations[course]?.[day]||[];periods[id]={goal,tasks:[planTask(day,id,course,'video',videos)]}};addPeriod('morning',morning,`${planCourseLabel(morning)}：完成视频并掌握本节核心方法`);addPeriod('afternoon',afternoon,`${planCourseLabel(afternoon)}：完成视频、笔记和当日例题`);const eveningCourses=[...new Set(pair)],eveningTasks=eveningCourses.map(code=>planTask(day,'evening',code,'practice',allocations[code]?.[day]||[]));if(day>='2026-09-08')eveningTasks.push(professionalPlanTask(day));periods.evening={goal:`${eveningCourses.map(planCourseLabel).join(' + ')}：巩固与检查${day>='2026-09-08'?'；专业课 2 小时':''}`,tasks:eveningTasks};plan[day]={day,rest:false,title:'课程计划',pair,periods}});planCache.value=plan;return plan}
function planForDay(day){return buildStudyPlan()[day]||null}
function planForSession(day,session){const plan=planForDay(day),id=session===schedule[0]?'morning':session===schedule[1]?'afternoon':session===schedule[2]?'evening':null;return id&&plan&&!plan.rest?{id,tasks:visiblePlanTasks(plan.periods[id].tasks)}:null}
function visiblePlanTasks(tasks){return (tasks||[]).filter(task=>!data.planDeletes?.[task.id])}
function planTasksForDay(day){const plan=planForDay(day);return plan&&!plan.rest?Object.values(plan.periods).flatMap(period=>visiblePlanTasks(period.tasks)):[]}
function sessionForPlanId(id){return id==='morning'?schedule[0]:id==='afternoon'?schedule[1]:id==='evening'?schedule[2]:null}
function planIdForSession(session){return session===schedule[0]?'morning':session===schedule[1]?'afternoon':session===schedule[2]?'evening':null}
function customTasksForPeriod(day,id){const session=sessionForPlanId(id);if(!session)return[];const key=periodKey(session);return data.tasks.filter(task=>task.dayKey===day&&task.sessionKey===key)}
function planPeriodsForDay(day){const plan=planForDay(day),periods=plan&&!plan.rest?Object.fromEntries(Object.entries(plan.periods).map(([id,period])=>[id,{...period,tasks:visiblePlanTasks(period.tasks)}]).filter(([,period])=>period.tasks.length)):{};['morning','afternoon','evening'].forEach(id=>{if(!periods[id]&&customTasksForPeriod(day,id).length)periods[id]={tasks:[]}});return periods}
function planCompletion(day){const planned=planTasksForDay(day),custom=['morning','afternoon','evening'].flatMap(id=>customTasksForPeriod(day,id)),tasks=[...planned,...custom],done=tasks.filter(task=>task.done||data.planChecks?.[task.id]).length;return{done,total:tasks.length,percent:tasks.length?Math.round(done/tasks.length*100):0}}
function editablePlanTask(task){const edit=data.planEdits?.[task.id];return edit?{...task,text:String(edit.text??task.text)}:task}
function findPlanTask(id){for(const task of Object.values(buildStudyPlan()).flatMap(day=>planTasksForDay(day.day))){if(task.id===id)return task}return null}
function planTaskMarkup(task,compact=false){const display=editablePlanTask(task),checked=!!data.planChecks?.[task.id],inputId=`plan-input-${task.id}`;return`<div class="plan-task ${checked?'done':''} ${compact?'compact':''}"><input id="${escapeHtml(inputId)}" type="checkbox" data-plan-id="${escapeHtml(task.id)}" ${checked?'checked':''}><label for="${escapeHtml(inputId)}"><strong>${escapeHtml(display.text)}</strong></label><button type="button" class="plan-edit" data-plan-edit="${escapeHtml(task.id)}" aria-label="编辑任务" title="编辑任务">编辑</button><button type="button" class="plan-edit plan-delete" data-plan-del="${escapeHtml(task.id)}" aria-label="删除任务" title="删除任务">删除</button></div>`}
function deletePlanTask(id){if(!id)return;data.planDeletes[id]=true;delete data.planChecks[id];delete data.planEdits[id];save();renderTimeline();renderTasks();renderCalendar();const modal=$('planModal');if(!modal.classList.contains('hidden'))openPlanModal(modal.dataset.day)}
function customTaskMarkup(task,compact=false){const checked=!!task.done,inputId=`task-input-${task.id}`;return`<div class="plan-task custom-plan-task ${checked?'done':''} ${compact?'compact':''}"><input id="${escapeHtml(inputId)}" type="checkbox" data-task-id="${escapeHtml(task.id)}" ${checked?'checked':''}><label for="${escapeHtml(inputId)}"><strong>${escapeHtml(task.text)}</strong></label><button type="button" class="plan-edit" data-custom-edit="${escapeHtml(task.id)}" aria-label="编辑任务" title="编辑任务">编辑</button><button type="button" class="plan-edit custom-task-delete" data-task-del="${escapeHtml(task.id)}" aria-label="删除任务" title="删除任务">删除</button></div>`}
function planPeriodMarkup(period,id,day){const custom=customTasksForPeriod(day,id).slice().sort((a,b)=>(Number(b.createdAt)||0)-(Number(a.createdAt)||0)),labels={morning:'上午',afternoon:'下午',evening:'晚上'};return`<section class="plan-period"><div class="plan-period-label">${labels[id]||''}</div>${custom.map(task=>customTaskMarkup(task)).join('')}${period.tasks.map(task=>planTaskMarkup(task)).join('')}</section>`}
function openPlanModal(day){const plan=planForDay(day),periods=planPeriodsForDay(day);$('planModal').dataset.day=day;$('planModalTitle').textContent=formatTaskDate(day);$('planModalMessage').textContent=plan?.rest?'今天是休息日，可以手动添加任务。':plan?'':'这一天不在当前课程计划范围内，但仍可添加自定义任务。';$('planModalBody').innerHTML=Object.keys(periods).length?Object.entries(periods).map(([id,period])=>planPeriodMarkup(period,id,day)).join(''):'<div class="empty">暂无预设课程计划。</div>';$('planModal').classList.remove('hidden')}
function openAddTask(day,periodId){$('addTaskModal').dataset.day=day;$('addTaskTitle').textContent=`${formatTaskDate(day)} · 新增任务`;$('addTaskPeriod').value=periodId||'morning';$('addTaskText').value='';$('addTaskError').textContent='';$('addTaskModal').classList.remove('hidden');$('addTaskText').focus()}
function closeAddTask(){$('addTaskModal').classList.add('hidden')}
function saveAddedTask(event){event.preventDefault();const modal=$('addTaskModal'),day=modal.dataset.day,text=$('addTaskText').value.trim(),periodId=$('addTaskPeriod').value,session=sessionForPlanId(periodId);if(!text||!session){$('addTaskError').textContent='请填写任务并选择时间段。';return}data.tasks.push({id:`task-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,text,done:false,createdAt:Date.now(),dayKey:day,sessionKey:periodKey(session),sessionTitle:session.title});save();closeAddTask();renderTimeline();renderTasks();renderCalendar();const planModal=$('planModal');if(!planModal.classList.contains('hidden'))openPlanModal(planModal.dataset.day)}
function deleteCustomTask(id){const task=data.tasks.find(item=>item.id===id);if(!task)return;data.tasks.splice(data.tasks.indexOf(task),1);save();renderTimeline();renderTasks();renderCalendar();const planModal=$('planModal');if(!planModal.classList.contains('hidden'))openPlanModal(planModal.dataset.day)}
function openPlanEdit(id){const task=findPlanTask(id);if(!task)return;const edit=data.planEdits?.[id]||{};$('planEditModal').dataset.task=id;$('planEditModal').dataset.custom='';$('planEditError').textContent='';$('planEditText').value=edit.text??task.text;$('planEditReset').classList.remove('hidden');$('planEditModal').classList.remove('hidden');$('planEditText').focus()}
function openCustomTaskEdit(id){const task=data.tasks.find(item=>item.id===id);if(!task)return;$('planEditModal').dataset.task=id;$('planEditModal').dataset.custom='1';$('planEditError').textContent='';$('planEditText').value=task.text;$('planEditReset').classList.add('hidden');$('planEditModal').classList.remove('hidden');$('planEditText').focus()}
function closePlanEdit(){$('planEditModal').classList.add('hidden')}
function savePlanEdit(event){event.preventDefault();const modal=$('planEditModal'),id=modal.dataset.task,text=$('planEditText').value.trim();if(!text){$('planEditError').textContent='任务不能为空。';return}$('planEditError').textContent='';if(modal.dataset.custom==='1'){const task=data.tasks.find(item=>item.id===id);if(!task)return;task.text=text}else{const task=findPlanTask(id);if(!task)return;if(text===task.text)delete data.planEdits[id];else data.planEdits[id]={text,updatedAt:Date.now()}}save();closePlanEdit();renderTimeline();renderTasks();renderCalendar();const planModal=$('planModal');if(!planModal.classList.contains('hidden'))openPlanModal(planModal.dataset.day)}
function resetPlanEdit(){const id=$('planEditModal').dataset.task;if(!id)return;delete data.planEdits[id];save();closePlanEdit();renderTimeline();renderTasks();renderCalendar();const planModal=$('planModal');if(!planModal.classList.contains('hidden'))openPlanModal(planModal.dataset.day)}
function previousStudyDay(key){const [y,m,d]=key.split('-').map(Number),date=new Date(y,m-1,d-1);while(date.getDay()===0)date.setDate(date.getDate()-1);return dateKey(date)}
function ensureCurrentDay(){const today=studyDayKey();if(!data.dayKey){data.dayKey=today;save();return}if(data.dayKey===today)return;let finalElapsed=Number(data.timer?.elapsed)||elapsed;if(data.timer?.running&&data.timer.startedAt){const [y,m,d]=data.dayKey.split('-').map(Number),cutoff=new Date(y,m-1,d+1,3,0,0).getTime();finalElapsed=Math.max(0,Math.floor((cutoff-data.timer.startedAt)/1000))}const settledMinutes=Math.max(0,Number(data.focused)||0)+Math.floor(Math.max(0,finalElapsed)/60),settledDate=new Date(`${data.dayKey}T12:00:00`);recordDailyFocus(data.dayKey,settledMinutes);if(settledDate.getDay()!==0){if(settledMinutes>0){data.streak=data.lastFocusDay===previousStudyDay(data.dayKey)?data.streak+1:1;data.lastFocusDay=data.dayKey}else data.streak=0}clearInterval(timerId);timerId=null;active=false;elapsed=0;data.dayKey=today;data.focused=0;data.interruptions=0;data.timer={running:false,startedAt:0,elapsed:0,changedAt:Date.now()};save()}
function formatMinutes(value){const minutes=Math.max(0,Number(value)||0),hours=Math.floor(minutes/60),restMinutes=minutes%60;return hours?`${hours} 小时 ${restMinutes} 分钟`:`${restMinutes} 分钟`}
function renderWeeklyFocus(){const chart=$('weeklyFocusChart');if(!chart)return;const today=new Date(),target=schedule.reduce((sum,item)=>sum+mins(item.end)-mins(item.start),0),weekdays=['日','一','二','三','四','五','六'];let html='';for(let offset=6;offset>=0;offset--){const date=new Date(today);date.setHours(12,0,0,0);date.setDate(today.getDate()-offset);const day=dateKey(date),isToday=day===dateKey(today),minutes=isToday?Math.max(Number(data.dailyFocus[day])||0,data.focused+Math.floor(elapsed/60)):Number(data.dailyFocus[day])||0,percent=target?Math.min(100,Math.round(minutes/target*100)):0;html+=`<div class="weekly-focus-day ${isToday?'today':''}" aria-label="${day}，专注 ${minutes} 分钟，完成度 ${percent}%"><div class="weekly-focus-value">${percent}%</div><div class="weekly-focus-track"><div class="weekly-focus-fill" style="height:${percent}%"></div></div><strong>${isToday?'今天':`周${weekdays[date.getDay()]}`}</strong><small>${date.getMonth()+1}/${date.getDate()}</small></div>`}$('weeklyFocusChart').innerHTML=html}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=`${y} 年 ${m+1} 月`;const first=new Date(y,m,1),offset=(first.getDay()+6)%7,total=new Date(y,m+1,0).getDate(),today=dateKey(new Date()),currentStudyDay=studyDayKey();let html='',monthMinutes=0;for(let i=0;i<offset;i++)html+='<span class="calendar-day empty-day"></span>';for(let d=1;d<=total;d++){const date=new Date(y,m,d),keyDate=dateKey(date),checked=!!data.checkins[keyDate],hasTasks=planCompletion(keyDate).total>0,recordedMinutes=Number(data.dailyFocus[keyDate])||0,liveMinutes=data.focused+Math.floor(elapsed/60),minutes=keyDate===currentStudyDay?Math.max(recordedMinutes,liveMinutes):recordedMinutes;monthMinutes+=minutes;html+=`<button class="calendar-day ${keyDate===today?'today ':''}${hasTasks?'has-plan ':''}${checked?'checked':''}" data-date="${keyDate}" aria-label="${keyDate}${checked?' 已签到':''}，专注 ${minutes} 分钟"><span>${d}</span>${minutes?`<small>${minutes}m</small>`:''}${checked?'<i>✓</i>':''}</button>`}$('calendar').innerHTML=html;$('monthlyFocus').textContent=`本月专注 ${formatMinutes(monthMinutes)}`;const todayChecked=!!data.checkins[today];$('checkinBtn').textContent=todayChecked?'今日已签到':'签到打卡';$('checkinBtn').disabled=todayChecked;$('checkinMessage').textContent=todayChecked?'今天的努力已经留下记录。':'点击日期可查看当天课程计划；签到按钮用于记录出勤。'}
function updateStats(){const target=schedule.reduce((sum,item)=>sum+mins(item.end)-mins(item.start),0),liveFocused=data.focused+Math.floor(elapsed/60),p=Math.min(100,Math.round(liveFocused/target*100));$('focusTarget').textContent=`今日进度 · 目标 ${formatMinutes(target)}`;$('progressPercent').textContent=`${p}%`;$('progressBar').style.width=p+'%';$('focusedMinutes').textContent=`${liveFocused} 分钟`;$('interruptions').textContent=`${data.interruptions} 次`;$('streak').textContent=`${data.streak} 天`}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){ensureCurrentDay();const sunday=new Date().getDay()===0,s=currentSession();$('sessionName').textContent=sunday?'休息日':s.title;$('todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});$('dayStatus').textContent=sunday?'今天休息':'准备开始';$('backgroundMode').checked=localStorage.getItem('focus-background-mode')==='1';renderTimeline();renderTasks();renderTaskHistory();renderIdeas();$('reviewInput').value=data.review||'';applyRemoteTimer();updateStats();renderWeeklyFocus();renderCalendar()}
function tick(){ensureCurrentDay();if(data.timer?.running)elapsed=Math.max(0,Math.floor((Date.now()-data.timer.startedAt)/1000));const h=String(Math.floor(elapsed/3600)).padStart(2,'0'),m=String(Math.floor(elapsed%3600/60)).padStart(2,'0'),s=String(elapsed%60).padStart(2,'0');$('timer').textContent=`${h}:${m}:${s}`;updateStats();renderWeeklyFocus();if(elapsed%60===0)renderCalendar()}
function start(){if(timerId)return;active=true;timerSource='local';const changedAt=Date.now();data.timer={running:true,startedAt:changedAt-elapsed*1000,elapsed,changedAt};save();tick();timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('timerHint').textContent='保持这一件事，其他念头放进收集箱';$('dayStatus').textContent='专注中'} function pause(){if(data.timer?.running){tick();recordDailyFocus(data.dayKey,data.focused+Math.floor(elapsed/60));data.timer={running:false,startedAt:0,elapsed,changedAt:Date.now()};save();renderCalendar()}clearInterval(timerId);timerId=null;$('startBtn').disabled=false;$('pauseBtn').disabled=true;$('dayStatus').textContent='已暂停'}
function applyRemoteTimer(){const t=data.timer;if(!t?.running){clearInterval(timerId);timerId=null;elapsed=Math.max(0,t?.elapsed||0);active=elapsed>0;tick();$('startBtn').disabled=false;$('pauseBtn').disabled=true;if(t)$('dayStatus').textContent='已暂停';return}active=true;timerSource='remote';elapsed=Math.max(0,Math.floor((Date.now()-t.startedAt)/1000));if(!timerId)timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('dayStatus').textContent='专注中';tick()}
function openIdea(prefill=''){ $('modalInput').value=prefill;$('ideaModal').classList.remove('hidden');$('modalInput').focus() } function addIdea(text){text=text.trim();if(!text)return;data.ideas.unshift({text,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});save();renderIdeas();$('ideaModal').classList.add('hidden')}
$('startBtn').onclick=start;
$('pauseBtn').onclick=pause;
$('taskForm').onsubmit=e=>{e.preventDefault();const t=$('taskInput').value.trim();if(t){const session=currentSession();data.tasks.push({id:`task-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,text:t,done:false,createdAt:Date.now(),dayKey:data.dayKey||studyDayKey(),sessionKey:periodKey(session),sessionTitle:session.title});$('taskInput').value='';save();renderTasks();renderTaskHistory()}};
function togglePlanTask(id,checked){if(!id)return;data.planChecks[id]=!!checked;save();renderTimeline();renderTasks();renderCalendar();const modal=$('planModal');if(!modal.classList.contains('hidden')){const day=modal.dataset.day;openPlanModal(day)}}
function handlePlanChange(e){const input=e.target.closest('[data-plan-id]');if(input)togglePlanTask(input.dataset.planId,input.checked)}
function handlePlanEditClick(e){const button=e.target.closest('[data-plan-edit]');if(!button)return;e.preventDefault();e.stopPropagation();openPlanEdit(button.dataset.planEdit)}
function handleCustomTaskChange(e){const input=e.target.closest('[data-task-id]');if(!input)return;const task=data.tasks.find(item=>item.id===input.dataset.taskId);if(!task)return;task.done=input.checked;save();renderTimeline();renderTasks();renderCalendar()}
function handleCustomTaskClick(e){const button=e.target.closest('[data-task-del]');if(!button)return;e.preventDefault();e.stopPropagation();deleteCustomTask(button.dataset.taskDel)}
$('taskList').onclick=e=>{const edit=e.target.closest('[data-plan-edit]');if(edit){handlePlanEditClick(e);return}const id=e.target.dataset.taskId||e.target.dataset.taskDel;if(!id)return;const task=data.tasks.find(item=>item.id===id);if(!task)return;if(e.target.dataset.taskId){task.done=e.target.checked}else{data.tasks.splice(data.tasks.indexOf(task),1)}save();renderTasks();renderTaskHistory()};
$('taskList').onchange=handlePlanChange;
$('timeline').onclick=e=>{handlePlanEditClick(e);handleCustomTaskClick(e)};
$('timeline').onchange=e=>{handlePlanChange(e);handleCustomTaskChange(e)};
$('planModalBody').onclick=e=>{const del=e.target.closest('[data-plan-del]');if(del&&!e.target.closest('[data-task-del]')){e.preventDefault();e.stopPropagation();deletePlanTask(del.dataset.planDel);return}handlePlanEditClick(e);handleCustomTaskClick(e)};
$('planModalBody').onchange=e=>{handlePlanChange(e);handleCustomTaskChange(e)};
$('taskHistoryBtn').onclick=()=>{$('taskHistoryModal').classList.remove('hidden');renderTaskHistory()};
$('taskHistoryClose').onclick=()=>$('taskHistoryModal').classList.add('hidden');
$('ideaForm').onsubmit=e=>{e.preventDefault();addIdea($('ideaInput').value);$('ideaInput').value=''};
$('modalSave').onclick=()=>addIdea($('modalInput').value);
$('modalClose').onclick=()=>$('ideaModal').classList.add('hidden');
$('overlayClose').onclick=()=>{$('focusOverlay').classList.add('hidden');if(resumeAfterLeave){resumeAfterLeave=false;start()}};
$('overlayCollect').onclick=()=>{resumeAfterLeave=false;$('focusOverlay').classList.add('hidden');openIdea()};
$('saveReview').onclick=()=>{data.review=$('reviewInput').value.trim();save();$('reviewSaved').textContent='已保存';setTimeout(()=>$('reviewSaved').textContent='',1800)};
function handleVisibilityChange(hidden=document.hidden){if(hidden&&data.timer?.running&&localStorage.getItem('focus-background-mode')!=='1'){data.interruptions++;pause();resumeAfterLeave=true;$('overlayTitle').textContent='刚才离开了一下，计时已暂停';$('overlayMessage').textContent='把注意力带回当前任务。想做的事可以先记下，回来后再继续计时。';$('focusOverlay').classList.remove('hidden');updateStats()}}
document.addEventListener('visibilitychange',()=>handleVisibilityChange());
document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA'].includes(tag))openIdea();});
const savedTheme=localStorage.getItem('focus-theme');if(savedTheme==='dark')document.body.classList.add('dark');$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('focus-theme',document.body.classList.contains('dark')?'dark':'light')};$('backgroundMode').onchange=e=>localStorage.setItem('focus-background-mode',e.target.checked?'1':'0');$('scheduleReminders').checked=localStorage.getItem('focus-schedule-reminders')==='1';$('scheduleReminders').onchange=async e=>{localStorage.setItem('focus-schedule-reminders',e.target.checked?'1':'0');localStorage.setItem('focus-last-period',periodKey(currentSession()));if(e.target.checked&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission()};$('testReminder').onclick=()=>showPeriodReminder(null,currentSession());$('reminderClose').onclick=()=>$('reminderModal').classList.add('hidden');if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});setInterval(()=>{renderTimeline();renderTasks()},60000);setInterval(syncFromServer,1000);setInterval(ensureCurrentDay,1000);setInterval(checkPeriodTransition,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkPeriodTransition();renderTasks()}});syncFromServer();render();checkPeriodTransition();
$('checkinBtn').onclick=()=>{const today=dateKey(new Date());if(!data.checkins[today]){data.checkins[today]={at:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})};save();renderCalendar()}};function changeCalendarMonth(offset){calendarDate.setDate(1);calendarDate.setMonth(calendarDate.getMonth()+offset);renderCalendar()}$('prevMonth').onclick=()=>changeCalendarMonth(-1);$('nextMonth').onclick=()=>changeCalendarMonth(1);$('calendar').onclick=e=>{const day=e.target.closest('[data-date]');if(day)openPlanModal(day.dataset.date)};$('planModal').dataset.day='';$('planModalClose').onclick=()=>$('planModal').classList.add('hidden');$('planAddTask').onclick=()=>openAddTask($('planModal').dataset.day);$('planEditForm').onsubmit=savePlanEdit;$('planEditClose').onclick=closePlanEdit;$('planEditReset').onclick=resetPlanEdit;$('addTaskForm').onsubmit=saveAddedTask;$('addTaskClose').onclick=closeAddTask;
$('editSchedule').onclick=openScheduleEditor;$('scheduleClose').onclick=()=>$('scheduleModal').classList.add('hidden');$('scheduleForm').onsubmit=saveScheduleEditor;$('resetSchedule').onclick=()=>{fillScheduleForm(defaultTimeline);$('scheduleError').textContent=''};
