const defaultTimeline=['09:00','12:00','13:30','18:00','20:30','23:00'];
const schedule=[{start:'09:00',end:'12:00',title:'上午复习',sub:'建立今天的节奏'},{start:'13:30',end:'18:00',title:'下午复习',sub:'完成当天的主要任务'},{start:'20:30',end:'23:00',title:'晚间复习',sub:'收束、巩固与整理'}];
const rest=[{start:'12:00',end:'13:30',title:'午饭与休息',sub:'离开书桌，真正休息'},{start:'18:00',end:'20:30',title:'晚饭与休息',sub:'给大脑换个频道'},{start:'23:00',end:'09:00',title:'陪伴与睡眠',sub:'今天到这里',overnight:true}];
const key='focus-guardian-v1', syncEndpoint=window.FOCUS_SYNC_ENDPOINT||'api/sync.php', syncToken=window.FOCUS_SYNC_TOKEN||''; let storedData=null;try{storedData=JSON.parse(localStorage.getItem(key)||'null')}catch(e){localStorage.removeItem(key)}let data=normalizeRemote(storedData);let active=null,elapsed=0,timerId=null,timerSource='local',writeBusy=false,writePending=false,readBusy=false;let calendarDate=new Date();
const $=id=>document.getElementById(id); const nowMinutes=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()}; const mins=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};
function syncHeaders(){return {'Content-Type':'application/json',...(syncToken?{'X-Sync-Token':syncToken}:{})}}
function setSyncStatus(text,good=false){const el=$('syncStatus');if(el){el.textContent=text;el.classList.toggle('online',good)}}
async function syncToServer(){if(writeBusy){writePending=true;return}writeBusy=true;const snapshot=JSON.stringify(data);try{const r=await fetch(syncEndpoint,{method:'PUT',headers:syncHeaders(),cache:'no-store',body:snapshot});if(!r.ok)throw new Error('sync failed');await r.json();localStorage.setItem('focus-sync-initialized','1');setSyncStatus('已同步',true)}catch(e){setSyncStatus('离线')}finally{writeBusy=false;if(writePending||JSON.stringify(data)!==snapshot){writePending=false;syncToServer()}}}
function timelineIsValid(values){return Array.isArray(values)&&values.length===6&&values.every(v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v))&&values.every((v,i)=>i===0||timeToMinutes(values[i-1])<timeToMinutes(v))}
function timeToMinutes(value){const [h,m]=value.split(':').map(Number);return h*60+m}
function applyTimelineConfig(values){const b=timelineIsValid(values)?values.slice():defaultTimeline.slice();schedule[0].start=b[0];schedule[0].end=b[1];rest[0].start=b[1];rest[0].end=b[2];schedule[1].start=b[2];schedule[1].end=b[3];rest[1].start=b[3];rest[1].end=b[4];schedule[2].start=b[4];schedule[2].end=b[5];rest[2].start=b[5];rest[2].end=b[0];return b}
function normalizeRemote(value){value=value||{};value.tasks=Array.isArray(value.tasks)?value.tasks:[];value.ideas=Array.isArray(value.ideas)?value.ideas:[];value.checkins=value.checkins||{};value.dailyFocus=value.dailyFocus||{};value.timeline=applyTimelineConfig(value.timeline);value.settings=value.settings||{};value.settings.backgroundMode=!!value.settings.backgroundMode;value.focused=Number(value.focused)||0;value.interruptions=Number(value.interruptions)||0;value.streak=Number(value.streak)||0;value.review=value.review||'';value.updatedAt=Number(value.updatedAt)||0;return value}
async function syncFromServer(){if(readBusy||writeBusy)return;readBusy=true;let uploadAfter=false;const localVersion=data.updatedAt;try{const r=await fetch(syncEndpoint,{headers:syncHeaders(),cache:'no-store'});if(!r.ok)throw new Error('sync failed');const payload=await r.json();if(payload.data&&data.updatedAt===localVersion){data=normalizeRemote(payload.data);localStorage.setItem(key,JSON.stringify(data));localStorage.setItem('focus-sync-initialized','1');render()}else if(payload.data===null&&!localStorage.getItem('focus-sync-initialized')&&(data.tasks.length||data.ideas.length||data.focused||Object.keys(data.checkins).length||data.timer?.running)){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));uploadAfter=true}else if(payload.data===null){localStorage.setItem('focus-sync-initialized','1')}setSyncStatus('已同步',true)}catch(e){setSyncStatus('本地')}finally{readBusy=false;if(uploadAfter)syncToServer()}}
function save(){data.updatedAt=Date.now();localStorage.setItem(key,JSON.stringify(data));syncToServer()} function isInWindow(s,n){const start=mins(s.start),end=mins(s.end);return s.overnight?n>=start||n<end:n>=start&&n<end} function currentSession(){const n=nowMinutes();return [...schedule,...rest].find(s=>isInWindow(s,n))||rest[2]}
function displayEnd(period){return period.overnight?`次日 ${period.end}`:period.end}
function periodKey(s){return `${s.start}-${s.end}`}
function showPeriodReminder(previous,current){const title=`${current.title}开始`,$modal=$('reminderModal');$('reminderTitle').textContent=title;$('reminderMessage').textContent=previous?`${previous.title}已结束。现在进入 ${current.start}–${displayEnd(current)} 的${current.title}。`:`现在进入 ${current.start}–${displayEnd(current)} 的${current.title}。`;if(document.visibilityState==='visible')$modal.classList.remove('hidden');else if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body:$('reminderMessage').textContent,icon:'assets/zinhologo.jpg'})}
function checkPeriodTransition(){const current=currentSession(),currentKey=periodKey(current),previousKey=localStorage.getItem('focus-last-period');if(previousKey&&previousKey!==currentKey&&localStorage.getItem('focus-schedule-reminders')==='1'&&new Date().getDay()!==0){const previous=[...schedule,...rest].find(s=>periodKey(s)===previousKey);showPeriodReminder(previous,current)}localStorage.setItem('focus-last-period',currentKey)}
function fillScheduleForm(values){values.forEach((value,index)=>$('scheduleTime'+index).value=value)}
function openScheduleEditor(){$('scheduleError').textContent='';fillScheduleForm(data.timeline);$('scheduleModal').classList.remove('hidden')}
function saveScheduleEditor(event){event.preventDefault();const values=defaultTimeline.map((_,index)=>$('scheduleTime'+index).value);if(!timelineIsValid(values)){$('scheduleError').textContent='六个时间必须按当天先后顺序排列，且不能相同。';return}data.timeline=applyTimelineConfig(values);localStorage.setItem('focus-last-period',periodKey(currentSession()));save();render();$('scheduleModal').classList.add('hidden')}
function renderTimeline(){const n=nowMinutes();$('timeline').innerHTML=[...schedule,...rest].sort((a,b)=>mins(a.start)-mins(b.start)).map(s=>{const is=isInWindow(s,n);return `<div class="timeline-row ${is?'active':''}"><span class="time">${s.start}<br>${displayEnd(s)}</span><div><div class="timeline-title">${s.title}</div><div class="timeline-sub">${s.sub}</div></div><span class="timeline-badge">${is?'进行中':'计划'}</span></div>`}).join('')}
function renderTasks(){ $('taskList').innerHTML=data.tasks.map((t,i)=>`<div class="task-item ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-i="${i}"><label>${escapeHtml(t.text)}</label><button class="delete-task" data-del="${i}" aria-label="删除">×</button></div>`).join('')||'<div class="empty">还没有任务，先写下这一段要完成的事。</div>'; $('taskCount').textContent=`${data.tasks.filter(t=>t.done).length}/${data.tasks.length||3}`}
function renderIdeas(){$('ideaList').innerHTML=data.ideas.map(i=>`<li>${escapeHtml(i.text)}<small>${i.time}</small></li>`).join('')||'<li class="empty">收集箱是空的，保持这份清爽。</li>';$('inboxCount').textContent=`${data.ideas.length} 条`}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function previousStudyDay(key){const [y,m,d]=key.split('-').map(Number),date=new Date(y,m-1,d-1);while(date.getDay()===0)date.setDate(date.getDate()-1);return dateKey(date)}
function ensureCurrentDay(){const today=dateKey(new Date());if(!data.dayKey){data.dayKey=today;save();return}if(data.dayKey===today)return;let finalElapsed=Number(data.timer?.elapsed)||elapsed;if(data.timer?.running&&data.timer.startedAt){const [y,m,d]=data.dayKey.split('-').map(Number),cutoff=new Date(y,m-1,d+1).getTime();finalElapsed=Math.max(0,Math.floor((cutoff-data.timer.startedAt)/1000))}const settledMinutes=data.focused+Math.floor(finalElapsed/60),settledDate=new Date(`${data.dayKey}T12:00:00`);data.dailyFocus[data.dayKey]=Math.max(Number(data.dailyFocus[data.dayKey])||0,settledMinutes);if(settledDate.getDay()!==0){if(settledMinutes>0){data.streak=data.lastFocusDay===previousStudyDay(data.dayKey)?data.streak+1:1;data.lastFocusDay=data.dayKey}else data.streak=0}clearInterval(timerId);timerId=null;active=false;elapsed=0;data.dayKey=today;data.focused=0;data.interruptions=0;data.timer={running:false,startedAt:0,elapsed:0,changedAt:Date.now()};save()}
function formatMinutes(value){const minutes=Math.max(0,Number(value)||0),hours=Math.floor(minutes/60),restMinutes=minutes%60;return hours?`${hours} 小时 ${restMinutes} 分钟`:`${restMinutes} 分钟`}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=`${y} 年 ${m+1} 月`;const first=new Date(y,m,1),offset=(first.getDay()+6)%7,total=new Date(y,m+1,0).getDate(),today=dateKey(new Date());let html='',monthMinutes=0;for(let i=0;i<offset;i++)html+='<span class="calendar-day empty-day"></span>';for(let d=1;d<=total;d++){const date=new Date(y,m,d),keyDate=dateKey(date),checked=!!data.checkins[keyDate],minutes=keyDate===today?data.focused+Math.floor(elapsed/60):Number(data.dailyFocus[keyDate])||0;monthMinutes+=minutes;html+=`<button class="calendar-day ${keyDate===today?'today ':''}${checked?'checked':''}" data-date="${keyDate}" aria-label="${keyDate}${checked?' 已签到':''}，专注 ${minutes} 分钟"><span>${d}</span>${minutes?`<small>${minutes}m</small>`:''}${checked?'<i>✓</i>':''}</button>`}$('calendar').innerHTML=html;$('monthlyFocus').textContent=`本月专注 ${formatMinutes(monthMinutes)}`;const todayChecked=!!data.checkins[today];$('checkinBtn').textContent=todayChecked?'今日已签到':'签到打卡';$('checkinBtn').disabled=todayChecked;$('checkinMessage').textContent=todayChecked?'今天的努力已经留下记录。':'觉得今天学得不错，就给自己留一个标记。'}
function updateStats(){const target=schedule.reduce((sum,item)=>sum+mins(item.end)-mins(item.start),0),liveFocused=data.focused+Math.floor(elapsed/60),p=Math.min(100,Math.round(liveFocused/target*100));$('focusTarget').textContent=`今日进度 · 目标 ${formatMinutes(target)}`;$('progressPercent').textContent=`${p}%`;$('progressBar').style.width=p+'%';$('focusedMinutes').textContent=`${liveFocused} 分钟`;$('interruptions').textContent=`${data.interruptions} 次`;$('streak').textContent=`${data.streak} 天`}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){ensureCurrentDay();const sunday=new Date().getDay()===0,s=currentSession();$('sessionName').textContent=sunday?'休息日':s.title;$('todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});$('dayStatus').textContent=sunday?'今天休息':'准备开始';$('backgroundMode').checked=data.settings.backgroundMode;renderTimeline();renderTasks();renderIdeas();$('reviewInput').value=data.review||'';applyRemoteTimer();updateStats();renderCalendar()}
function tick(){ensureCurrentDay();if(data.timer?.running)elapsed=Math.max(0,Math.floor((Date.now()-data.timer.startedAt)/1000));const h=String(Math.floor(elapsed/3600)).padStart(2,'0'),m=String(Math.floor(elapsed%3600/60)).padStart(2,'0'),s=String(elapsed%60).padStart(2,'0');$('timer').textContent=`${h}:${m}:${s}`;updateStats();if(elapsed%60===0)renderCalendar()}
function start(){if(timerId)return;active=true;timerSource='local';const changedAt=Date.now();data.timer={running:true,startedAt:changedAt-elapsed*1000,elapsed,changedAt};save();tick();timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('timerHint').textContent='保持这一件事，其他念头放进收集箱';$('dayStatus').textContent='专注中'} function pause(){if(data.timer?.running){tick();data.timer={running:false,startedAt:0,elapsed,changedAt:Date.now()};save()}clearInterval(timerId);timerId=null;$('startBtn').disabled=false;$('pauseBtn').disabled=true;$('dayStatus').textContent='已暂停'}
function applyRemoteTimer(){const t=data.timer;if(!t?.running){clearInterval(timerId);timerId=null;elapsed=Math.max(0,t?.elapsed||0);active=elapsed>0;tick();$('startBtn').disabled=false;$('pauseBtn').disabled=true;if(t)$('dayStatus').textContent='已暂停';return}active=true;timerSource='remote';elapsed=Math.max(0,Math.floor((Date.now()-t.startedAt)/1000));if(!timerId)timerId=setInterval(tick,1000);$('startBtn').disabled=true;$('pauseBtn').disabled=false;$('dayStatus').textContent='专注中';tick()}
function openIdea(prefill=''){ $('modalInput').value=prefill;$('ideaModal').classList.remove('hidden');$('modalInput').focus() } function addIdea(text){text=text.trim();if(!text)return;data.ideas.unshift({text,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});save();renderIdeas();$('ideaModal').classList.add('hidden')}
$('startBtn').onclick=start;$('pauseBtn').onclick=pause;$('taskForm').onsubmit=e=>{e.preventDefault();const t=$('taskInput').value.trim();if(t){data.tasks.push({text:t,done:false});$('taskInput').value='';save();renderTasks()}};$('taskList').onclick=e=>{const i=e.target.dataset.i;if(i!==undefined){data.tasks[i].done=e.target.checked;save();renderTasks()}const d=e.target.dataset.del;if(d!==undefined){data.tasks.splice(d,1);save();renderTasks()}};$('ideaForm').onsubmit=e=>{e.preventDefault();addIdea($('ideaInput').value);$('ideaInput').value=''};$('modalSave').onclick=()=>addIdea($('modalInput').value);$('modalClose').onclick=()=>$('ideaModal').classList.add('hidden');$('overlayClose').onclick=()=>$('focusOverlay').classList.add('hidden');$('overlayCollect').onclick=()=>{ $('focusOverlay').classList.add('hidden');openIdea()};$('saveReview').onclick=()=>{data.review=$('reviewInput').value.trim();save();$('reviewSaved').textContent='已保存';setTimeout(()=>$('reviewSaved').textContent='',1800)};
function handleVisibilityChange(hidden=document.hidden){if(hidden&&data.timer?.running&&!data.settings.backgroundMode){data.interruptions++;pause();$('overlayTitle').textContent='刚才离开了一下，计时已暂停';$('overlayMessage').textContent='把注意力带回当前任务。想做的事可以先记下，回来后再继续计时。';$('focusOverlay').classList.remove('hidden');updateStats()}}
document.addEventListener('visibilitychange',()=>handleVisibilityChange());
document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName;if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA'].includes(tag))openIdea();});
const savedTheme=localStorage.getItem('focus-theme');if(savedTheme==='dark')document.body.classList.add('dark');$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('focus-theme',document.body.classList.contains('dark')?'dark':'light')};$('backgroundMode').onchange=e=>{data.settings.backgroundMode=e.target.checked;save()};$('scheduleReminders').checked=localStorage.getItem('focus-schedule-reminders')==='1';$('scheduleReminders').onchange=async e=>{localStorage.setItem('focus-schedule-reminders',e.target.checked?'1':'0');localStorage.setItem('focus-last-period',periodKey(currentSession()));if(e.target.checked&&'Notification'in window&&Notification.permission==='default')await Notification.requestPermission()};$('testReminder').onclick=()=>showPeriodReminder(null,currentSession());$('reminderClose').onclick=()=>$('reminderModal').classList.add('hidden');if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});setInterval(renderTimeline,60000);setInterval(syncFromServer,1000);setInterval(ensureCurrentDay,1000);setInterval(checkPeriodTransition,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkPeriodTransition()});syncFromServer();render();checkPeriodTransition();
$('checkinBtn').onclick=()=>{const today=dateKey(new Date());if(!data.checkins[today]){data.checkins[today]={at:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})};save();renderCalendar()}};$('prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$('calendar').onclick=e=>{const day=e.target.closest('[data-date]');if(!day)return;const k=day.dataset.date;if(data.checkins[k]){delete data.checkins[k];save();renderCalendar()}};
$('editSchedule').onclick=openScheduleEditor;$('scheduleClose').onclick=()=>$('scheduleModal').classList.add('hidden');$('scheduleForm').onsubmit=saveScheduleEditor;$('resetSchedule').onclick=()=>{fillScheduleForm(defaultTimeline);$('scheduleError').textContent=''};
